
server:
  port: 8090
spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=name, shuang
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

dubbo:
  application:
    name: dubbo-springboot-demo-provider
    qosPort: 33333
  protocol:
    name: dubbo
    port: 22223
  registry:
    id: nacos-registry
    address: nacos://localhost:8848
